In [70]:
import torch
import torch.nn.functional

In [71]:
arr4x4 = torch.arange(0., 16., requires_grad=True).view(4, 4)
arr4x4

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]], grad_fn=<ViewBackward0>)

In [72]:
torch.nn.functional.pad(arr4x4, ((1, 1)), mode='constant')
# arr4x4.take(index=0)

tensor([[ 0.,  0.,  1.,  2.,  3.,  0.],
        [ 0.,  4.,  5.,  6.,  7.,  0.],
        [ 0.,  8.,  9., 10., 11.,  0.],
        [ 0., 12., 13., 14., 15.,  0.]], grad_fn=<ConstantPadNdBackward0>)

In [73]:
# 'constant', 'reflect', 'replicate' or 'circular'
mode = 'circular'
tmp = torch.nn.functional.pad(arr4x4.unsqueeze(0), pad=(1, 1), mode=mode)
tmp = tmp.squeeze(0)
tmp

tensor([[ 3.,  0.,  1.,  2.,  3.,  0.],
        [ 7.,  4.,  5.,  6.,  7.,  4.],
        [11.,  8.,  9., 10., 11.,  8.],
        [15., 12., 13., 14., 15., 12.]], grad_fn=<SqueezeBackward1>)

In [74]:
tmp = torch.nn.functional.pad((tmp.T).unsqueeze(0), pad=(1, 1), mode=mode)
tmp
# torch.nn.functional.pad(arr4x4.take(index=1), ((1, 1)), mode='constant')

tensor([[[15.,  3.,  7., 11., 15.,  3.],
         [12.,  0.,  4.,  8., 12.,  0.],
         [13.,  1.,  5.,  9., 13.,  1.],
         [14.,  2.,  6., 10., 14.,  2.],
         [15.,  3.,  7., 11., 15.,  3.],
         [12.,  0.,  4.,  8., 12.,  0.]]], grad_fn=<CopySlices>)

In [75]:
tmp[0, 1, 1] = 1.
tmp

tensor([[[15.,  3.,  7., 11., 15.,  3.],
         [12.,  1.,  4.,  8., 12.,  0.],
         [13.,  1.,  5.,  9., 13.,  1.],
         [14.,  2.,  6., 10., 14.,  2.],
         [15.,  3.,  7., 11., 15.,  3.],
         [12.,  0.,  4.,  8., 12.,  0.]]], grad_fn=<CopySlices>)

In [77]:
arr4x4

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]], grad_fn=<ViewBackward0>)

In [76]:
# import torch
# dx = torch.zeros(size=(4, 4), requires_grad=True)
# dy = torch.zeros(size=(4, 4), requires_grad=True)

# tv_iso = torch.sum(torch.sqrt( dx**2 + dy**2 ))
# tv_iso.backward()
tmp.requires_grad

True

In [60]:
arr4x4 = torch.arange(0., 16.).view(4, 4)
arr4x4

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])

In [62]:
derivation(arr4x4, axis=1, detach=False)

tensor([[-12., -12., -12., -12.],
        [  4.,   4.,   4.,   4.],
        [  4.,   4.,   4.,   4.],
        [  4.,   4.,   4.,   4.]])


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])

In [38]:
t = torch.narrow(arr4x4, dim=0, start=0, length=2)
t -= 1
t

tensor([[-1.,  0.,  1.,  2.],
        [ 3.,  4.,  5.,  6.]])

In [39]:
arr4x4

tensor([[-1.,  0.,  1.,  2.],
        [ 3.,  4.,  5.,  6.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])

In [52]:
import torch

# Example tensor with 4 dimensions
my_tensor = arr4x4

# Index of the dimension you want to select
index = 0

# Determine the number of dimensions
num_dims = my_tensor.dim()

# Create a range of indices to select the desired dimension
indices = torch.arange(0, num_dims)

# Replace the index with the desired dimension index
indices[index] = num_dims - 1

# Use torch.index_select to select the dimension
t = torch.index_select(my_tensor, dim=indices[index], index=torch.arange(my_tensor.size(index)))

# Print the resulting tensor
print(t.shape)

torch.Size([4, 4])


In [78]:
import torch
dx = torch.zeros(size=(4, 4), requires_grad=False)
dy = torch.zeros(size=(4, 4), requires_grad=True)
d = dx + dy
d.requires_grad

True