In [1]:
import numpy
import scipy.signal
import sys
sys.path.append('..')

In [2]:
import lasp.utils
import lasp.filters.linear

In [3]:
lap = lasp.filters.linear.laplacian()
lap_circshifted = lasp.utils.pad_circshift_center(lap, (5, 5))
print(lap_circshifted)

[[ 4 -1  0  0 -1]
 [-1  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [-1  0  0  0  0]]


In [6]:
dx_oper = numpy.array([[1, -1]])
dx_oper_circshifted = lasp.utils.pad_circshift_center(dx_oper, (5, 5))
print(dx_oper_circshifted)

[[ 0  0  0  0  0]
 [ 1 -1  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]]


In [8]:
lap = lasp.filters.linear.laplacian()
shape = numpy.array(lap.shape)
center = lasp.utils.compute_center(lap)

lap_circshifted = lasp.utils.pad_circshift_center(lap, (5, 5))
print(lap_circshifted)

lap_circshifted_reverse = lasp.utils.circshift(lap_circshifted, shape-center)
print(lap_circshifted_reverse)

[[ 4 -1  0  0 -1]
 [-1  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [-1  0  0  0  0]]
[[ 0 -1  0  0  0]
 [-1  4 -1  0  0]
 [ 0 -1  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]]
