In [2]:
import scipy.signal
import numpy
import sys
sys.path.append('..')

In [3]:
import lasp.differential
import lasp.utils
import lasp.filters.linear

In [4]:
arr = numpy.reshape(numpy.arange(0, 16), (4, 4))
arr_fft = numpy.fft.fft2(arr) # img in frequency domain
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


## dx

In [5]:
# Derivation
dx_oper = numpy.array([[ 1, -1 ]]) # operator


## With convolution (ie spatial domain)
arr_dx_v1 = scipy.signal.convolve2d(
    arr, 
    dx_oper, 
    mode='same',
    boundary='wrap'
)


## With point wise product
### Spatial convolution becomes a point wise product in frequency domain
### For apply a filter in frequency domain, you must padded filter with
### even dimensions that image then you make point wise product in frequency doamin
dx_oper_pad = lasp.utils.pad(dx_oper, arr.shape)
dx_oper_pad_fft = numpy.fft.fft2(dx_oper_pad) # operator in frequency domain
arr_dx_fft_v2 = dx_oper_pad_fft * arr_fft # Point wise product in frequency domain
arr_dx_v2 = numpy.real(numpy.fft.ifft2(arr_dx_fft_v2)) # Return in sptial


# ## BCCB tricks
dx_oper_diag = lasp.utils.fourier_diagonalization(dx_oper, arr.shape)
arr_fft_dx_v3 = dx_oper_diag * arr_fft
arr_dx_v3 = numpy.real(numpy.fft.ifft2(arr_fft_dx_v3))


## With numpy
arr_dx_v4 = lasp.differential.dx(arr)

print(arr_dx_v1)
print(arr_dx_v2)
print(arr_dx_v3)
print(arr_dx_v4)

[[-3  1  1  1]
 [-3  1  1  1]
 [-3  1  1  1]
 [-3  1  1  1]]
[[-3.  1.  1.  1.]
 [-3.  1.  1.  1.]
 [-3.  1.  1.  1.]
 [-3.  1.  1.  1.]]
[[-3.  1.  1.  1.]
 [-3.  1.  1.  1.]
 [-3.  1.  1.  1.]
 [-3.  1.  1.  1.]]
[[-3.  1.  1.  1.]
 [-3.  1.  1.  1.]
 [-3.  1.  1.  1.]
 [-3.  1.  1.  1.]]


## dy

In [6]:
# Derivation
dy_oper = numpy.transpose(numpy.array([[ 1, -1 ]])) # operator


## With convolution (ie spatial domain)
arr_dy_v1 = scipy.signal.convolve2d(
    arr, 
    dy_oper, 
    mode ='same',
    boundary = 'wrap'
)


## With point wise product
### Spatial convolution becomes a point wise product in frequency domain
### For apply a filter in frequency domain, you must padded filter with
### even dimensions that image then you make point wise product in frequency doamin
dy_oper_pad = lasp.utils.pad(dy_oper, arr.shape)
dy_oper_pad_fft = numpy.fft.fft2(dy_oper_pad) # operator in frequency domain
arr_dy_fft_v2 = dy_oper_pad_fft * arr_fft # Point wise product in frequency domain
arr_dy_v2 = numpy.real(numpy.fft.ifft2(arr_dy_fft_v2)) # Return in sptial


# ## BCCB tricks
dy_oper_diag = lasp.utils.fourier_diagonalization(dy_oper, arr.shape)
arr_fft_dy_v3 = dy_oper_diag * arr_fft
arr_dy_v3 = numpy.real(numpy.fft.ifft2(arr_fft_dy_v3))


## With numpy
arr_dy_v4 = lasp.differential.dy(arr)

print(arr_dy_v1)
print(arr_dy_v2)
print(arr_dy_v3)
print(arr_dy_v4)

[[-12 -12 -12 -12]
 [  4   4   4   4]
 [  4   4   4   4]
 [  4   4   4   4]]
[[-12. -12. -12. -12.]
 [  4.   4.   4.   4.]
 [  4.   4.   4.   4.]
 [  4.   4.   4.   4.]]
[[-12. -12. -12. -12.]
 [  4.   4.   4.   4.]
 [  4.   4.   4.   4.]
 [  4.   4.   4.   4.]]
[[-12. -12. -12. -12.]
 [  4.   4.   4.   4.]
 [  4.   4.   4.   4.]
 [  4.   4.   4.   4.]]


## dxT

In [7]:
# Derivation

dx_oper = numpy.array([[ 1, -1 ]]) # operator

## With point wise product
### Spatial convolution becomes a point wise product in frequency domain
### For apply a filter in frequency domain, you must padded filter with
### even dimensions that image then you make point wise product in frequency doamin
dx_oper_pad = lasp.utils.pad(dx_oper, arr.shape)
dx_oper_pad_fft = numpy.fft.fft2(dx_oper_pad)
dxT_oper_pad_fft = numpy.conj(dx_oper_diag)
arr_dxT_fft_v1 = dxT_oper_pad_fft * arr_fft # Point wise product in frequency domain
arr_dxT_v1 = numpy.real(numpy.fft.ifft2(arr_dxT_fft_v1)) # Return in sptial


# ## BCCB tricks
# Derivation
dx_oper_diag = lasp.utils.fourier_diagonalization(dx_oper, arr.shape)
dxT_oper_diag = numpy.conj(dx_oper_diag)
arr_fft_dxT_v2 = dxT_oper_diag * arr_fft
arr_dxT_v2 = numpy.real(numpy.fft.ifft2(arr_fft_dxT_v2))


## With numpy
arr_dxT_v3 = lasp.differential.dxT(arr)

print('Convolution :', 'Not spatial operator')
print('Hadamard in Fourier:\n', arr_dxT_v1)
print('BCCB :\n', arr_dxT_v2)
print('dxT :\n', arr_dxT_v3)

Convolution : Not spatial operator
Hadamard in Fourier:
 [[-1. -1. -1.  3.]
 [-1. -1. -1.  3.]
 [-1. -1. -1.  3.]
 [-1. -1. -1.  3.]]
BCCB :
 [[-1. -1. -1.  3.]
 [-1. -1. -1.  3.]
 [-1. -1. -1.  3.]
 [-1. -1. -1.  3.]]
dxT :
 [[-1. -1. -1.  3.]
 [-1. -1. -1.  3.]
 [-1. -1. -1.  3.]
 [-1. -1. -1.  3.]]


## dyT

In [8]:
# Derivation

dy_oper = numpy.transpose(numpy.array([[ 1, -1 ]])) # operator

## With point wise product
### Spatial convolution becomes a point wise product in frequency domain
### For apply a filter in frequency domain, you must padded filter with
### even dimensions that image then you make point wise product in frequency doamin
dy_oper_pad = lasp.utils.pad(dy_oper, arr.shape)
dy_oper_pad_fft = numpy.fft.fft2(dy_oper_pad)
dyT_oper_pad_fft = numpy.conj(dy_oper_diag)
arr_dyT_fft_v1 = dyT_oper_pad_fft * arr_fft # Point wise product in frequency domain
arr_dyT_v1 = numpy.real(numpy.fft.ifft2(arr_dyT_fft_v1)) # Return in sptial


# ## BCCB tricks
# Derivation
dy_oper_diag = lasp.utils.fourier_diagonalization(dy_oper, arr.shape)
dyT_oper_diag = numpy.conj(dy_oper_diag)
arr_fft_dyT_v2 = dyT_oper_diag * arr_fft
arr_dyT_v2 = numpy.real(numpy.fft.ifft2(arr_fft_dyT_v2))


## With numpy
arr_dyT_v3 = lasp.differential.dyT(arr)

print('Convolution :', 'Not spatial operator')
print('Hadamard in Fourier:\n', arr_dyT_v1)
print('BCCB :\n', arr_dyT_v2)
print('dxT :\n', arr_dyT_v3)

Convolution : Not spatial operator
Hadamard in Fourier:
 [[-4. -4. -4. -4.]
 [-4. -4. -4. -4.]
 [-4. -4. -4. -4.]
 [12. 12. 12. 12.]]
BCCB :
 [[-4. -4. -4. -4.]
 [-4. -4. -4. -4.]
 [-4. -4. -4. -4.]
 [12. 12. 12. 12.]]
dxT :
 [[-4. -4. -4. -4.]
 [-4. -4. -4. -4.]
 [-4. -4. -4. -4.]
 [12. 12. 12. 12.]]


## Laplacian

In [9]:
x_oper = numpy.array([[ 1, -1 ]]) # operator
dx_oper_pad = lasp.utils.pad(dx_oper, arr.shape)
dx_oper_pad_fft = numpy.fft.fft2(dx_oper_pad)
dxT_oper_pad_fft = numpy.conj(dx_oper_diag)

dy_oper = numpy.transpose(numpy.array([[ 1, -1 ]])) # operator
dy_oper_pad = lasp.utils.pad(dy_oper, arr.shape)
dy_oper_pad_fft = numpy.fft.fft2(dy_oper_pad)
dyT_oper_pad_fft = numpy.conj(dy_oper_diag)

lap_pad_fft_v1 = \
    dxT_oper_pad_fft * dx_oper_pad_fft \
    + dyT_oper_pad_fft * dy_oper_pad_fft

arr_lap_fft_v1 = lap_pad_fft_v1 * arr_fft
arr_lap_v1 = numpy.real(numpy.fft.ifft(arr_lap_fft_v1))

###########################

lap_filter = lasp.filters.linear.laplacian()
print('lap filter :\n', lap_filter)

lap_pad_v2 = lasp.utils.pad(lap_filter, arr.shape)
lap_pad_fft_v2 = numpy.fft.fft2(lap_pad_v2)

arr_lap_fft_v2 = lap_pad_fft_v2 * arr_fft
arr_lap_v2 = numpy.real(numpy.fft.ifft2(arr_lap_fft_v2))

###########################

print('\nResults :\n')
print('Lap v1 :\n', arr_lap_v1)
print('lap v2 :\n', arr_lap_v2)

lap filter :
 [[ 0 -1  0]
 [-1  4 -1]
 [ 0 -1  0]]

Results :

Lap v1 :
 [[-16.   0.   0.  16.]
 [-16. -16. -16. -16.]
 [-32. -32. -32. -32.]
 [-16. -16. -16. -16.]]
lap v2 :
 [[ 20.  12.  16.  16.]
 [-12. -20. -16. -16.]
 [  4.  -4.   0.   0.]
 [  4.  -4.   0.   0.]]


In [10]:
laplacian = lasp.filters.linear.laplacian()
lap_diag_v1 = lasp.utils.fourier_diagonalization(
    kernel = laplacian,
    shape_out = arr.shape 
)

arr_lap_fft_v1 = lap_diag_v1 * arr_fft
arr_lap_v1 = numpy.real(numpy.fft.ifft(arr_lap_fft_v1))

Dx_pad = lasp.utils.pad(numpy.array([[1, -1]]), arr.shape)
Dx = numpy.fft.fft2(Dx_pad)
Dxt = numpy.conj(Dx)

Dy_pad = lasp.utils.pad(numpy.transpose(numpy.array([[1, -1]])), arr.shape)
Dy = numpy.fft.fft2(Dy_pad)
Dyt = numpy.conj(Dy)

Dx_diag = lasp.utils.fourier_diagonalization(
    kernel = Dx_pad,
    shape_out = arr.shape 
)
Dxt_diag = numpy.conj(Dx_diag)

Dy_diag = lasp.utils.fourier_diagonalization(
    kernel = Dy_pad,
    shape_out = arr.shape 
)
Dyt_diag = numpy.conj(Dy_diag)

lap_diag_v2 = Dxt_diag * Dx_diag + Dyt_diag * Dy_diag

arr_lap_fft_v1 = lap_diag_v2 * arr_fft
arr_lap_v1 = numpy.real(numpy.fft.ifft(arr_lap_fft_v2))

###

F2D = Dxt*Dx+Dyt*Dy

print('With laplacian filter :\n', arr_lap_v1)
print('With laplacian definition :\n', arr_lap_v2)
print((F2D == lap_diag_v2))

With laplacian filter :
 [[ 16. -16.   0.   0.]
 [ 16.  16.  16.  16.]
 [ 32.  32.  32.  32.]
 [ 16.  16.  16.  16.]]
With laplacian definition :
 [[ 20.  12.  16.  16.]
 [-12. -20. -16. -16.]
 [  4.  -4.   0.   0.]
 [  4.  -4.   0.   0.]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
