In [10]:
import sys
sys.path.append('..')

In [11]:
import lasp.differential
import numpy

In [12]:
shape = (4, 5)



In [13]:
grad = numpy.array(
    [
        lasp.differential.differential_matrix(lasp.differential.dx, shape),
        lasp.differential.differential_matrix(lasp.differential.dy, shape)
    ]
)
print(grad[0])
print(grad[1])

[[ 1. -1.  0.  0.  0.]
 [ 0.  1. -1.  0.  0.]
 [ 0.  0.  1. -1.  0.]
 [ 0.  0.  0.  1. -1.]]
[[ 1.  0.  0. -1.  0.]
 [-1.  1.  0.  0.  0.]
 [ 0. -1.  1.  0.  0.]
 [ 0.  0. -1.  1.  0.]]


In [14]:
gradT = numpy.array(
    [
        lasp.differential.differential_matrix(lasp.differential.dxT, shape),
        lasp.differential.differential_matrix(lasp.differential.dyT, shape)
    ]
)
print(gradT[0])
print(gradT[1])

[[ 1.  0.  0.  0. -1.]
 [-1.  1.  0.  0.  0.]
 [ 0. -1.  1.  0.  0.]
 [ 0.  0. -1.  1.  0.]]
[[ 1. -1.  0.  0.  0.]
 [ 0.  1. -1.  0.  0.]
 [ 0.  0.  1. -1.  0.]
 [-1.  0.  0.  1.  0.]]


In [15]:
print((gradT[0] == grad[1]).all())
print((gradT[1] == grad[0]).all())


False
False


In [16]:
# (grad[0] @ grad[0].T) + (grad[1] @ grad[1].T)

In [17]:
(grad[0].T @ grad[0]) + (grad[1].T @ grad[1])

array([[ 3., -2.,  0., -1.,  0.],
       [-2.,  4., -2.,  0.,  0.],
       [ 0., -2.,  4., -2.,  0.],
       [-1.,  0., -2.,  4., -1.],
       [ 0.,  0.,  0., -1.,  1.]])

In [18]:
(gradT[0] * grad[0]) + (gradT[1] * grad[1])

array([[ 2., -0.,  0.,  0.,  0.],
       [-0.,  2., -0.,  0.,  0.],
       [ 0., -0.,  2., -0.,  0.],
       [ 0.,  0., -0.,  2.,  0.]])