In [1]:
import numpy

In [18]:
d = numpy.zeros((5, 6))
m, n = numpy.shape(d)
c = min(m, n)

identity = numpy.eye(c, c)

print(identity.shape, d[0:c, 0:c].shape, d[m-c:, n-c:].shape)

d[0:c, 0:c] -= identity
d[m-c:, n-c:] += identity

print(d)

(5, 5) (5, 5) (5, 5)
[[-1.  1.  0.  0.  0.  0.]
 [ 0. -1.  1.  0.  0.  0.]
 [ 0.  0. -1.  1.  0.  0.]
 [ 0.  0.  0. -1.  1.  0.]
 [ 0.  0.  0.  0. -1.  1.]]


In [3]:
diag = d.diagonal(offset=1)
diag[:] = 1
print(diag, d)

ValueError: assignment destination is read-only

In [29]:
def D(n: int) -> numpy.ndarray:
    d = numpy.zeros((n, n+1))
    identity = numpy.eye(n, n)
    d[0:n, 0:n] -= identity
    d[0:n, 1:n+1] += identity
    return d

In [30]:
D(4)

array([[-1.,  1.,  0.,  0.,  0.],
       [ 0., -1.,  1.,  0.,  0.],
       [ 0.,  0., -1.,  1.,  0.],
       [ 0.,  0.,  0., -1.,  1.]])

In [33]:
a = numpy.reshape(numpy.arange(0, 9), (3, 3))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [35]:
v = numpy.reshape(a, newshape=(-1, 1), order='F')

In [36]:
v.shape

(9, 1)

In [2]:
import scipy.fft
import numpy

scipy.fft.fft2(numpy.eye(4, 4))

array([[4.-0.j, 0.+0.j, 0.-0.j, 0.-0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 4.-0.j],
       [0.-0.j, 0.+0.j, 4.-0.j, 0.-0.j],
       [0.-0.j, 4.+0.j, 0.-0.j, 0.-0.j]])