In [1]:
import sys
sys.path.append('..')

In [2]:
import numpy
import lasp.utils

In [3]:
arr = numpy.arange(1, 10).reshape((3, 3))
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
lasp.utils.pad(arr, shape_out=numpy.array([10, 10]))

array([[1, 2, 3, 0, 0, 0, 0, 0, 0, 0],
       [4, 5, 6, 0, 0, 0, 0, 0, 0, 0],
       [7, 8, 9, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [5]:
numpy.pad(arr, (2, 2), 'wrap')

array([[5, 6, 4, 5, 6, 4, 5],
       [8, 9, 7, 8, 9, 7, 8],
       [2, 3, 1, 2, 3, 1, 2],
       [5, 6, 4, 5, 6, 4, 5],
       [8, 9, 7, 8, 9, 7, 8],
       [2, 3, 1, 2, 3, 1, 2],
       [5, 6, 4, 5, 6, 4, 5]])

In [6]:
numpy.pad(arr, (2, 2), 'constant')

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 2, 3, 0, 0],
       [0, 0, 4, 5, 6, 0, 0],
       [0, 0, 7, 8, 9, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [27]:
numpy.pad(arr, [(0, 0), (0, 0)], 'reflect')

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
numpy.pad(arr, [(0, 1), (0, 1)], mode='constant')

array([[1, 2, 3, 0],
       [4, 5, 6, 0],
       [7, 8, 9, 0],
       [0, 0, 0, 0]])