In [85]:
import numpy
import scipy.signal

In [86]:
size = 3
filter = numpy.arange(0, size*size).reshape((size, size))
filter

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [87]:
N, M = 6, 6
arr = numpy.arange(0, N*M).reshape((N, M)).astype(float)
arr

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34., 35.]])

In [88]:
res1 = scipy.signal.convolve2d(
    in1=arr, 
    in2=filter, 
    mode='same', 
    boundary='wrap'
)

res2 = scipy.signal.convolve2d(
    in1=arr, 
    in2=filter, 
    mode='full', 
    boundary='wrap'
)

(res1 == res2[size//2:-size//2+1, size//2:-size//2+1]).all()

True

In [89]:
res1 = scipy.signal.convolve2d(
    in1=arr, 
    in2=filter, 
    mode='same', 
    boundary='wrap'
)

res2 = scipy.signal.convolve2d(
    in1=numpy.pad(arr, pad_width= [ (1, 1), (1, 1) ], mode='wrap'), 
    in2=filter,
    mode='valid'
)

(res1 == res2).all()

True

In [97]:
res1 = scipy.signal.convolve2d(
    in1=arr, 
    in2=numpy.flip(filter, axis=[0, 1]), 
    mode='same', 
    boundary='wrap'
)

res2 = numpy.flip(
    scipy.signal.convolve2d(
        in1=numpy.flip(arr, axis=[0, 1]), 
        in2=filter, 
        mode='same', 
        boundary='wrap'
    )
)

(res1 == res2).all()

True

In [98]:
res1

array([[ 276.,  258.,  294.,  330.,  366.,  312.],
       [ 384.,  366.,  402.,  438.,  474.,  420.],
       [ 600.,  582.,  618.,  654.,  690.,  636.],
       [ 816.,  798.,  834.,  870.,  906.,  852.],
       [1032., 1014., 1050., 1086., 1122., 1068.],
       [ 492.,  474.,  510.,  546.,  582.,  528.]])

In [99]:
res2

array([[ 276.,  258.,  294.,  330.,  366.,  312.],
       [ 384.,  366.,  402.,  438.,  474.,  420.],
       [ 600.,  582.,  618.,  654.,  690.,  636.],
       [ 816.,  798.,  834.,  870.,  906.,  852.],
       [1032., 1014., 1050., 1086., 1122., 1068.],
       [ 492.,  474.,  510.,  546.,  582.,  528.]])

In [ ]:
res1 = scipy.signal.convolve2d(
    in1=arr, 
    in2=filter, 
    mode='same', 
    boundary='wrap'
)

res2 = scipy.signal.convolve2d(
    in1=numpy.pad(arr, pad_width= [ (1, 1), (1, 1) ], mode='wrap'), 
    in2=filter,
    mode='valid'
)

# (res1 == res2[size//2:-size//2+1, size//2:-size//2+1]).all()
print(res1)
print(res2)