In [1]:
import numpy

In [23]:
arr = numpy.arange(0, 16)
arr = arr.reshape((4, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [24]:
arr.take(-1, axis=0)

array([12, 13, 14, 15])

In [25]:
numpy.diff(
    arr, 
    prepend=numpy.array([arr.take(-1, axis=0)]),
    # append=numpy.array([arr.take(-1, axis=0)]), 
    axis=0
)

array([[-12, -12, -12, -12],
       [  4,   4,   4,   4],
       [  4,   4,   4,   4],
       [  4,   4,   4,   4]])

In [26]:
numpy.diff(
    arr, 
    prepend=,
    # append=numpy.array([arr.take(-1, axis=0)]), 
    axis=1
)

array([[-3,  1,  1,  1],
       [-3,  1,  1,  1],
       [-3,  1,  1,  1],
       [-3,  1,  1,  1]])

In [27]:
numpy.transpose(numpy.array([arr.take(-1, axis=1)]))

array([[ 3],
       [ 7],
       [11],
       [15]])

array([[ 3],
       [ 7],
       [11],
       [15]])

In [36]:
oui = arr.take(indices=-1, axis=1)
oui


array([ 3,  7, 11, 15])

In [38]:
oui.take(indices=None)

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

In [ ]:
import sys
sys.append()