In [1]:
import numpy

a = numpy.array(
    [
        [1, 1],
        [1, 1]
    ]
)

a2 = numpy.stack([a.copy(), a.copy()+1])
print(a2)

def add(a, b) -> int:
    return a+b

add_vectorized = numpy.vectorize(add)

add_vectorized(a2[:, 0], a2[:, 1])


[[[1 1]
  [1 1]]

 [[2 2]
  [2 2]]]


array([[2, 2],
       [4, 4]])

In [2]:
numpy.min(a2, axis=0)

array([[1, 1],
       [1, 1]])

In [3]:
def histogram(image_greyscale: numpy.ndarray) -> numpy.ndarray:
    return numpy.histogram(image_greyscale, bins=256, range=(0, 255))[0]

    # m, n = image_greyscale.shape
    # hist = numpy.zeros(shape=256)
    # for i in range(0, m):
    #     for j in range(0, n):
    #         hist[image_greyscale[m, n]] += 1
    # return hist

In [4]:
histogram(numpy.array([[0, 1], [1, 255]]))

array([1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [8]:
a = numpy.arange(0, 4).reshape((2, 2))
print(a)
numpy.flip(a, 1)

[[0 1]
 [2 3]]


array([[1, 0],
       [3, 2]])